#!/bin/bash
. "$(dirname $0)/utils.sh"
run-safe
if ! which emacs > /dev/null ; then exit 0 ; fi
assure-extra-opkg-repo
opkg install emacs
exit 0


#### It is possible to build it from scratch
### FYI: /tmp is not large enough for the build.
#cd /home/root
#install-this http://ftp.gnu.org/gnu/emacs/ emacs-24.3

